# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macOS 10.13'

variables:
- group: React Native Variables

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    cd ios
    bundle install
    fastlane build
  displayName: 'Build iOS'
- script: |
    cd android
    bundle install
    fastlane build
  displayName: 'Build android'